Add new MavenHello project and update .gitignore with adding target
RipaAloyan/Java_Automation_Homework pull request #2
Opened 2021-03-15 16:26 UTC by RipaAloyan

2021-03-15 16:46 UTC, chandranik90 requested changes

2021-03-15 16:46 UTC, chandranik90 commented on MavenHello/pom.xml
> +    <artifactId>MavenHello</artifactId>
Please follow the naming convention for Maven. artifactId should be all lowercase
https://maven.apache.org/guides/mini/guide-naming-conventions.html

2021-03-15 16:51 UTC, RipaAloyan commented
Yes, thank you.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
From: Andranik Chorokhyan ***@***.***>
Sent: Monday, March 15, 2021 8:47:11 PM
To: RipaAloyan/Java_Automation_Homework ***@***.***>
Cc: Hripsime Aloyan ***@***.***>; Author ***@***.***>
Subject: Re: [RipaAloyan/Java_Automation_Homework] Add new MavenHello project and update .gitignore with adding target (#2)


@chandranik90 requested changes on this pull request.

________________________________

In MavenHello/pom.xml<https://urldefense.com/v3/__https://github.com/RipaAloyan/Java_Automation_Homework/pull/2*discussion_r594505597__;Iw!!GF_29dbcQIUBPA!hKqYYph8okUCjPpc511MX82-gIveE6kJGX4qWBJQUwswKf0h0pH7AadBcBlDIHV2bhs$>:

> @@ -0,0 +1,16 @@
+<?xml version="1.0" encoding="UTF-8"?>
+<project xmlns="http://maven.apache.org/POM/4.0.0"<https://urldefense.com/v3/__http://maven.apache.org/POM/4.0.0*22__;JQ!!GF_29dbcQIUBPA!hKqYYph8okUCjPpc511MX82-gIveE6kJGX4qWBJQUwswKf0h0pH7AadBcBlDzIqfePo$>
+         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
+         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"><https://urldefense.com/v3/__http://maven.apache.org/xsd/maven-4.0.0.xsd*22*3E__;JSU!!GF_29dbcQIUBPA!hKqYYph8okUCjPpc511MX82-gIveE6kJGX4qWBJQUwswKf0h0pH7AadBcBlD4PbOYOM$>
+    <modelVersion>4.0.0</modelVersion>
+
+    <groupId>org.example</groupId>
+    <artifactId>MavenHello</artifactId>


Please follow the naming convention for Maven. artifactId should be all lowercase
https://maven.apache.org/guides/mini/guide-naming-conventions.html<https://urldefense.com/v3/__https://maven.apache.org/guides/mini/guide-naming-conventions.html__;!!GF_29dbcQIUBPA!hKqYYph8okUCjPpc511MX82-gIveE6kJGX4qWBJQUwswKf0h0pH7AadBcBlDv5DcRQs$>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https://github.com/RipaAloyan/Java_Automation_Homework/pull/2*pullrequestreview-612418177__;Iw!!GF_29dbcQIUBPA!hKqYYph8okUCjPpc511MX82-gIveE6kJGX4qWBJQUwswKf0h0pH7AadBcBlDIwAWCk8$>, or unsubscribe<https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/ATCU3PKBFZM7WR7OFMVKBVTTDY2Y7ANCNFSM4ZG4BPHA__;!!GF_29dbcQIUBPA!hKqYYph8okUCjPpc511MX82-gIveE6kJGX4qWBJQUwswKf0h0pH7AadBcBlDv4j1Nc8$>.

2021-03-15 19:35 UTC, testforham approved these changes

2021-03-16 07:31 UTC, chandranik90 approved these changes

2021-03-16 16:47 UTC, merged